# Generated by Django 3.2.9 on 2022-01-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('description', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('image', models.URLField(blank=True)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
