# Generated by Django 3.2.9 on 2022-02-08 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20220208_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
