# Generated by Django 3.2.9 on 2022-02-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auctionlistings_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
